### ISSUE TITLE
这个文件会报错,

### ISSUE THREAD

**Issue by Meeca** [WuXuBaiYang/jtech_anime#1]
这个文件会报错,要怎么解决呢
<img width="1368" alt="image" src="https://github.com/WuXuBaiYang/jtech_anime/assets/8274946/dcc701aa-acfc-40db-9891-bed560c828dd">

**Comment by WuXuBaiYang** [comment]
在项目根目录下执行 dart pub run build_runner watch --verbose 生成数据库文件

**Comment by Meeca** [comment]
iOS 可以跑起来了,
但是用安卓手机就会启动不了,会出现下面的信息,
<img width="1087" alt="image" src="https://github.com/WuXuBaiYang/jtech_anime/assets/8274946/5d21af95-ea47-48e3-962e-226500316a45">
感谢!感谢

**Comment by Meeca** [comment]
我新开的项目,把您项目中引用的库引入,当添加到media_kit_libs_android_video 时,项目就会跑不起来,  请问下您是怎么解决的呢

**Comment by WuXuBaiYang** [comment]
这个问题是 flutter_meedu_videoplayer 依赖导致的，目前没有找到解决方案，正在全力重做视频播放器部分，近几天会发布到dev分支下
